# Deep Research Configuration

# OpenAI settings
openai:
  api_key: "sk-xxx"  # Set your OpenAI API key here
  base_url: "https://api.openai.com/v1"
  model: "gpt-4o-mini"  # Default model, can be "gpt-4o", "gpt-4o-mini"

# Report LLM settings
report_llm:
  api_key: "sk-xxx"  # Set your OpenAI API key here
  base_url: "https://api.openai.com/v1"
  model: "gpt-4o"

# Serper settings
serper:
  api_key: "xxx"  # Set your Serper API key here
  base_url: "https://google.serper.dev/search"

# Tavily settings
tavily:
  api_key: "tvly-dev-xxx"  # Use the token without 'Bearer' prefix
  base_url: "https://api.tavily.com/search"

# Research settings
research:
  concurrency_limit: 3 # 并发搜索数量
  context_size: 64000 # 传入LLM的最大文本长度（token数）
  search_source: "tavily" # 搜索引擎
  max_results_per_query: 3 # 每个搜索结果的最大数量
  enable_refine_search_result: False # 是否需要精简搜索结果，如果为True，将会对搜索结果提取关键片段；如果是False，直接用搜索结果原文
  enable_next_plan: False # 是否需要下一步计划，如果为True，将会总结搜索结果并提供下一步计划，为生成报告提供参考；如果是False，不要下一步计划的分析
  enable_clarification: False # 是否需要澄清问题，如果为True, 将会先澄清问题；如果是False，将会跳过澄清环节，直接进行搜索
